service:
  name: feed
  icon: http://cdn.problogdesign.com/wp-content/uploads/2008/04/f-monofactor.jpg
  description: rss or atom feed
  auth_type: noauth
  auth_data:
  helper:

trigger:
- name: subscribe
  description: subscribe a feed
  http_type: direct
  http_method: get
  period: * */1 * * *
  in_keys: [feed]
  source: \#{feed}
  out_keys: [title, link, content]
  content_to_hash: >
    x = xml(content)
    if ( (x / 'rss') > 0 )
      ret = (x / 'rss > channel > item').inject([]) do |item|
        {
          :title => (item / 'title').inner_text,
          :content => (item / 'description').inner_text,
          :link => (item / 'link').inner_text,
          :published => Time.parse((item / 'pubDate').inner_text)
        }
    end
    if ( (x / 'feed') > 0 )
      ret = (x / 'feed > entry').inject([]) do |item|
        {
          :title => (item / 'title').inner_text,
          :content => (item / 'content').inner_text,
          :link => (item / 'link').inner_text,
          :published => Time.parse((item / 'updated').inner_text)
        }
    end
    ret

action:
