service:
  name: 新浪微博
  icon: http://www.sinaimg.cn/blog/developer/wiki/LOGO_64x64.png
  description: 大眼新浪微博
  auth_type: oauth1a
  auth_data:
    key: input your twitter consumer key
    secret: input your twitter consumer secret
    auth_site: http://api.t.sina.com.cn
    access_site: https://api.weibo.com/2
    request_token_source: /oauth/request_token
    access_token_source: /oauth/access_token
    authorize_source: /oauth/authorize
    signature_method: HMAC-SHA1
    scheme: header
  helper:

trigger:
- name: 自己的微博
  description: 自己发布的微博
  http_type: oauth1a
  http_method: get
  period: */10 * * * *
  in_keys: []
  source: /statuses/user_timeline.json
  out_keys: [text, in_reply_to_user, source]
  content_to_hash: >
    body = json(content)
    body["statuses"].each do |item|
      {
        :text => item["text"],
        :in_reply_to_user => item["in_reply_to_screen_name"],
        :source => item["source"].gsub(/<.*?>/, ''),
        :published => Time.parse(item["created_at"])
      }
    end

- name: tweets no reply
  description: users tweets with special tag
  http_type: twitter
  http_method: get
  period: */10 * * * *
  in_keys: [tag]
  source: /statuses/user_timeline.json
  out_keys: [text, source]
  content_to_hash: >
    ret = parse_json content do |item|
      {
        :text => item["text"],
        :source => item["source"].gsub(/<.*?>/, ''),
        :published => Time.parse(item["created_at"])
      }
    end
    ret.select { |i| i[:text].find "\##{tag}\#" }

action:
- name: 发布微博
  description: 发布一条微博
  http_type: oauth1a
  http_method: post
  in_keys: [status]
  target: /statuses/update.json
  body: >
    status
